name: Firebase Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build For Hosting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: |
          cd hosting
          yarn
      - name: Build
        run: |
          cd hosting
          yarn build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: hosting/dist
  deploy:
    name: Deploy for Hosting
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: hosting/dist
      - name: Deploy to Firebase
        run: |
          yarn global add firebase-tools
          firebase deploy --only hosting --token=${{ secrets.FIREBASE_TOKEN }}
# 現状、Dockerのエラーでfailureなってしまうので、手動でDeployを実現している。
#   deploy:
#     name: Deploy for Hosting
#     needs: build
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Repo
#         uses: actions/checkout@master
#       - name: Download Artifact
#         uses: actions/download-artifact@master
#         with:
#           name: dist
#           path: hosting/dist
#       - name: Deploy to Firebase
#         uses: w9jds/firebase-action@master
#         with:
#           args: deploy --only hosting:prod
#         env:
#           FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
